name: Deploy lambda_payalert
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  release:
    name: Deploy lambda_payalert
    runs-on: [ ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: MySessionName
      - name: zip lambda_payalert
        run: |
          zip -r9 lambda.zip lambda_payalert.py
      - name: AWS Deploy
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:297098627551:function:Slack_payroll_notification --zip-file fileb://lambda.zip
          aws lambda invoke --function-name arn:aws:lambda:us-east-1:297098627551:function:Slack_payroll_notification --cli-binary-format raw-in-base64-out --payload '{ "key": "value" }' response.yml
          
